nome = input('Digite seu nome: ')
print('Seu nome em Maiúsculo é \033[31m{}\033[m'.format(nome.upper()))
print('Seu nome em Minúsculo é \033[32m{}\033[m'.format(nome.lower()))
print('Seu nome tem ao todo \033[33m{}\033[m letras'.format(len(nome)-nome.count(' ')))
#print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é \033[34m{}\033[m e ele tem \033[35m{}\033[m letras'.format(separa[0], len(separa[0])))
